-- Hand-added, not generated by drizzle-kit: the trigram indexes below need
-- pg_trgm. It is a trusted extension: any role with CREATE on the database can add it.
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
-- Hand-added: stop, rather than fail on the seed's unique index, when a live
-- customer tenant already holds the now-reserved slug.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "tenants" WHERE "slug" = 'platform' AND "deleted_at" IS NULL) THEN
    RAISE EXCEPTION 'migration 0016: a live tenant already uses the reserved slug "platform"; rename it before upgrading';
  END IF;
END $$;--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" varchar(36) PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"occurred_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"actor_kind" varchar(10) NOT NULL,
	"actor_user_id" varchar(36),
	"access" varchar(10) NOT NULL,
	"tenant_id" varchar(36) NOT NULL,
	"action" varchar(64) NOT NULL,
	"target_type" varchar(32),
	"target_id" varchar(36),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"request_id" varchar(64),
	"ip" varchar(45),
	"user_agent" varchar(512),
	CONSTRAINT "audit_logs_actor_kind_check" CHECK ("audit_logs"."actor_kind" in ('user', 'system')),
	CONSTRAINT "audit_logs_access_check" CHECK ("audit_logs"."access" in ('member', 'platform', 'system')),
	CONSTRAINT "audit_logs_actor_user_check" CHECK (("audit_logs"."actor_kind" = 'system') = ("audit_logs"."actor_user_id" is null)),
	CONSTRAINT "audit_logs_action_check" CHECK ("audit_logs"."action" ~ '^[a-z]+(\.[a-z_]+)+$'),
	CONSTRAINT "audit_logs_target_type_check" CHECK ("audit_logs"."target_type" is null or "audit_logs"."target_type" in ('tenant', 'membership', 'invitation', 'settings', 'user')),
	CONSTRAINT "audit_logs_target_check" CHECK (("audit_logs"."target_type" is null) = ("audit_logs"."target_id" is null))
);
--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "is_platform" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_logs_tenant_occurred_idx" ON "audit_logs" USING btree ("tenant_id","occurred_at","id");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_occurred_idx" ON "audit_logs" USING btree ("actor_user_id","occurred_at","id");--> statement-breakpoint
CREATE INDEX "audit_logs_occurred_idx" ON "audit_logs" USING btree ("occurred_at","id");--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_single_platform" ON "tenants" USING btree ((true)) WHERE "tenants"."is_platform";--> statement-breakpoint
CREATE INDEX "tenants_name_trgm_idx" ON "tenants" USING gin (lower("name") gin_trgm_ops) WHERE "tenants"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "tenants_slug_trgm_idx" ON "tenants" USING gin ("slug" gin_trgm_ops) WHERE "tenants"."deleted_at" is null;--> statement-breakpoint
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_platform_active" CHECK (not "tenants"."is_platform" or ("tenants"."lifecycle_state" = 'active' and "tenants"."deleted_at" is null));--> statement-breakpoint
-- Hand-added: the platform tenant and its settings row. It has no members
-- until `pnpm platform:grant` runs.
INSERT INTO "tenants" ("name", "slug", "is_platform") VALUES ('Platform', 'platform', true);--> statement-breakpoint
INSERT INTO "tenant_settings" ("tenant_id") SELECT "id" FROM "tenants" WHERE "is_platform";--> statement-breakpoint
-- Hand-added: audit_logs is append-only. Every UPDATE and DELETE raises, with
-- no exceptions. TRUNCATE is left open on purpose, for test and ops resets.
CREATE FUNCTION "audit_logs_immutable"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only';
END;
$$;--> statement-breakpoint
CREATE TRIGGER "audit_logs_immutable" BEFORE UPDATE OR DELETE ON "audit_logs" FOR EACH ROW EXECUTE FUNCTION "audit_logs_immutable"();