// src/scripts/generate-env-example.ts
//
// Inside src/ on purpose: it imports `@/configs/env.config`, and at the
// repo-root scripts/ path it would sit outside tsconfig's `include`, so
// `tsc --noEmit` would skip it and eslint's type-aware parser would error
// on it. core uses src/scripts/ for exactly this class of tool.
//
// .env.example is generated, never hand-edited. A hand-maintained example
// file drifts from the schema within weeks, and the drift is invisible until
// someone's first run fails.
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { EnvSchemaShape } from '@/configs/env.config'

/**
 * A default or example as it is written after `KEY=`.
 * @param value - A parsed default or a `.meta({ example })` value.
 * @returns The text form, or `undefined` for anything that is not a scalar.
 */
function asEnvText(value: unknown): string | undefined {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  return undefined
}

/**
 * The value one field is written with in `.env.example`, if it has one.
 *
 * The default comes from parsing `undefined`, not from the JSON schema: with
 * `io: 'input'`, a `z.stringbool().default(true)` carries no `default` there,
 * because its input is a string and its default a boolean.
 * @param schema - One field of the environment schema.
 * @param example - The field's `.meta({ example })` value, if any.
 * @returns The value to write, or `undefined` when the field has none.
 */
function exampleValue(schema: z.ZodType, example: unknown): string | undefined {
  const parsed = schema.safeParse(undefined)
  if (parsed.success && parsed.data !== undefined) return asEnvText(parsed.data)
  // A required field with no default: write its example, if it has one.
  return asEnvText(example)
}

/**
 * Render `.env.example` file content from the environment schema's field map.
 * @param shape - The schema's field map (`EnvSchema.shape`), keyed by environment variable name.
 * @returns The full `.env.example` file content, including the generated-file header.
 */
export function render(shape: Record<string, z.ZodType>): string {
  const lines: string[] = ['# Generated by `pnpm env:example`. Do not edit by hand.', '']

  for (const [key, schema] of Object.entries(shape)) {
    const json = z.toJSONSchema(schema, { target: 'openapi-3.0', io: 'input' })
    const description = typeof json.description === 'string' ? json.description : ''
    const value = exampleValue(schema, json.example)
    // A field with no value that still accepts undefined is genuinely
    // optional (e.g. OTEL_EXPORTER_OTLP_ENDPOINT, or COOKIE_SECURE, whose
    // default is derived from APP_ENV in code). Emit it commented out: an
    // uncommented `KEY=` looks identical to a required field left blank.
    const isOptional = value === undefined && schema.safeParse(undefined).success
    if (description) lines.push(`# ${description}`)
    lines.push(`${isOptional ? '# ' : ''}${key}=${value ?? ''}`, '')
  }

  return lines.join('\n')
}

// Only write the file when this module is run directly (`pnpm env:example`),
// not when `render`/`EnvSchemaShape` are imported by a test.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync('.env.example', render(EnvSchemaShape))
}
