/**
 * @file Generates `.env.example` (and ARCHITECTURE.md's environment table)
 * from the environment schema, so the example never drifts from it. Lives in
 * src/ because it imports `@/configs/env.config`, and outside src/ it would
 * fall outside tsconfig's `include`, unchecked by `tsc` and type-aware ESLint.
 * `pnpm env:example` writes the file; `pnpm env:table` passes `--table` and
 * prints the table.
 */
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { EnvSchemaShape } from '@/configs/env.config'

/**
 * A default or example as it is written after `KEY=`.
 * @param value - A parsed default or a `.meta({ example })` value.
 * @returns The text form, or `undefined` for anything that is not a scalar.
 */
function asEnvText(value: unknown): string | undefined {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  return undefined
}

/**
 * The value one field is written with in `.env.example`, if it has one.
 *
 * The default comes from parsing `undefined`, not from the JSON schema: with
 * `io: 'input'`, a `z.stringbool().default(true)` carries no `default` there,
 * because its input is a string and its default a boolean.
 * @param schema - One field of the environment schema.
 * @param example - The field's `.meta({ example })` value, if any.
 * @returns The value to write, or `undefined` when the field has none.
 */
function exampleValue(schema: z.ZodType, example: unknown): string | undefined {
  const parsed = schema.safeParse(undefined)
  if (parsed.success && parsed.data !== undefined) return asEnvText(parsed.data)
  return asEnvText(example)
}

/**
 * Render `.env.example` file content from the environment schema's field map.
 * An optional field with no value is written commented out, since a bare
 * `KEY=` would look like a required field left blank.
 * @param shape - The schema's field map (`EnvSchema.shape`), keyed by environment variable name.
 * @returns The full `.env.example` file content, including the generated-file header.
 */
export function render(shape: Record<string, z.ZodType>): string {
  const lines: string[] = ['# Generated by `pnpm env:example`. Do not edit by hand.', '']

  for (const [key, schema] of Object.entries(shape)) {
    const json = z.toJSONSchema(schema, { target: 'openapi-3.0', io: 'input' })
    const description = typeof json.description === 'string' ? json.description : ''
    const value = exampleValue(schema, json.example)
    const isOptional = value === undefined && schema.safeParse(undefined).success
    if (description) lines.push(`# ${description}`)
    lines.push(`${isOptional ? '# ' : ''}${key}=${value ?? ''}`, '')
  }

  return lines.join('\n')
}

/**
 * Render ARCHITECTURE.md's environment table from the environment schema's
 * field map.
 *
 * One row per field, in schema order: whether it is required, its default,
 * and its `.describe()` text with `|` escaped. The output is unpadded;
 * prettier pads the columns once it is pasted into ARCHITECTURE.md.
 * @param shape - The schema's field map (`EnvSchema.shape`), keyed by environment variable name.
 * @returns The Markdown table, header row first, with no trailing newline.
 */
export function renderEnvTable(shape: Record<string, z.ZodType>): string {
  const rows = Object.entries(shape).map(([key, schema]) => {
    const json = z.toJSONSchema(schema, { target: 'openapi-3.0', io: 'input' })
    const text = typeof json.description === 'string' ? json.description : ''
    const unset = schema.safeParse(undefined)
    const required = unset.success ? 'no' : '**yes**'
    const defaultText = unset.success ? asEnvText(unset.data) : undefined
    const fallback = defaultText === undefined ? '—' : `\`${defaultText}\``
    const escaped = text.replaceAll('|', String.raw`\|`)
    return `| \`${key}\` | ${required} | ${fallback} | ${escaped} |`
  })
  return [
    '| Variable | Required | Default | What it does |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--table')) {
    process.stdout.write(`${renderEnvTable(EnvSchemaShape)}\n`)
  } else {
    fs.writeFileSync('.env.example', render(EnvSchemaShape))
  }
}
