// src/scripts/generate-env-example.ts
//
// Inside src/ on purpose: it imports `@/configs/env.config`, and at the
// repo-root scripts/ path it would sit outside tsconfig's `include`, so
// `tsc --noEmit` would skip it and eslint's type-aware parser would error
// on it. core uses src/scripts/ for exactly this class of tool.
//
// .env.example is generated, never hand-edited. A hand-maintained example
// file drifts from the schema within weeks, and the drift is invisible until
// someone's first run fails.
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { EnvSchemaShape } from '@/configs/env.config'

/**
 * Render `.env.example` file content from the environment schema's field map.
 * @param shape - The schema's field map (`EnvSchema.shape`), keyed by environment variable name.
 * @returns The full `.env.example` file content, including the generated-file header.
 */
export function render(shape: Record<string, z.ZodType>): string {
  const lines: string[] = ['# Generated by `pnpm env:example`. Do not edit by hand.', '']

  for (const [key, schema] of Object.entries(shape)) {
    const json = z.toJSONSchema(schema, { target: 'openapi-3.0', io: 'input' })
    const hasDefault = typeof json === 'object' && 'default' in json
    const description = typeof json === 'object' && 'description' in json ? json.description : ''
    const fallback = hasDefault ? String(json.default) : ''
    // A field with no default that still accepts undefined is genuinely
    // optional (e.g. OTEL_EXPORTER_OTLP_ENDPOINT). Emit it commented out:
    // an uncommented `KEY=` looks identical to a required field left blank,
    // and a reader cannot tell "no value needed" from "fill this in".
    // Fields with a default are never commented — their fallback is already
    // a usable value, not a placeholder.
    // `schema.isOptional()` is deprecated in zod 4 in favour of this exact
    // safe-parse check (see the schema's own deprecation notice).
    const isOptional = !hasDefault && schema.safeParse(undefined).success
    if (description) lines.push(`# ${description}`)
    lines.push(`${isOptional ? '# ' : ''}${key}=${fallback}`, '')
  }

  return lines.join('\n')
}

// Only write the file when this module is run directly (`pnpm env:example`),
// not when `render`/`EnvSchemaShape` are imported by a test.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync('.env.example', render(EnvSchemaShape))
}
