import { describe, expect, it } from 'vitest'
import { EnvSchemaShape } from '@/configs/env.config'
import { render } from '@/scripts/generate-env-example'

describe('render', () => {
  const output = render(EnvSchemaShape)

  it('includes the generated-file header', () => {
    expect(output).toContain('# Generated by `pnpm env:example`. Do not edit by hand.')
  })

  it('includes every key from the schema shape', () => {
    for (const key of Object.keys(EnvSchemaShape)) {
      expect(output).toContain(`${key}=`)
    }
  })

  it('renders the description for a documented field as a comment', () => {
    expect(output).toContain('# Public origin of the frontend.')
  })

  it('has no JWT_REFRESH_SECRET field at all — refresh tokens are opaque, not JWTs', () => {
    expect(Object.keys(EnvSchemaShape)).not.toContain('JWT_REFRESH_SECRET')
    expect(output).not.toContain('JWT_REFRESH_SECRET')
  })

  // Three fields that all graduated out of the same "PLACEHOLDER — nothing
  // reads this yet" note, at three different points in this repo's history,
  // once something in src/ actually started reading them:
  // JWT_ACCESS_SECRET earliest (session.service.ts signs/verifies access
  // tokens with it), then APP_URL and SESSION_SECRET together in this task
  // (passport.config.ts's `configurePassport()`/`createOAuthSessionMiddleware()`
  // read them respectively). One parameterized test, not three near-identical
  // ones (sonarjs/parameterized-tests) — each case still pins its own
  // `.describe()` text landing in the generated file, not merely that SOME
  // description exists.
  it.each([
    { field: 'JWT_ACCESS_SECRET', expectedText: 'Signs and verifies access tokens' },
    {
      field: 'APP_URL',
      expectedText: 'Used to build the Google OAuth callback URL',
    },
    { field: 'SESSION_SECRET', expectedText: 'Signs the express-session cookie' },
    { field: 'APP_NAME', expectedText: 'Product name in outbound email copy' },
  ])(
    'describes what $field actually does, not a stale placeholder note',
    ({ field, expectedText }) => {
      const index = output.indexOf(`${field}=`)
      const preceding = output.slice(Math.max(0, index - 300), index)
      expect(preceding).toContain(expectedText)
      expect(preceding).not.toContain('PLACEHOLDER')
    }
  )

  it('renders a schema default value', () => {
    expect(output).toContain('APP_PORT=4040')
  })

  it('comments out a genuinely optional field with no default', () => {
    expect(output).toContain('# OTEL_EXPORTER_OTLP_ENDPOINT=')
  })

  it('does not comment out a required field', () => {
    expect(output).toContain('\nDATABASE_URL=\n')
    expect(output).not.toContain('# DATABASE_URL=')
  })

  it('does not comment out a field with a default', () => {
    expect(output).toContain('\nAPP_PORT=4040\n')
  })

  // io: 'input' JSON schema drops a stringbool's default (its input is a
  // string, its default a boolean), which used to render `# WORKER_ENABLED=`.
  it('renders a z.stringbool() default as its value, uncommented', () => {
    expect(output).toContain('\nWORKER_ENABLED=true\n')
    expect(output).not.toContain('# WORKER_ENABLED=')
  })

  it('renders a required enum with its example value, uncommented', () => {
    expect(output).toContain('\nAPP_ENV=local\n')
    expect(output).toContain('\nNODE_ENV=development\n')
    expect(output).not.toContain('# APP_ENV=')
  })

  it.each(['COOKIE_SECURE', 'LOG_FORMAT'])(
    'comments out %s, whose default comes from APP_ENV in code',
    (key) => {
      const index = output.indexOf(`# ${key}=\n`)
      expect(index).toBeGreaterThan(-1)
      const preceding = output.slice(Math.max(0, index - 300), index)
      expect(preceding).toContain('Defaults from APP_ENV')
    }
  )

  it('renders every new numeric default', () => {
    for (const line of [
      'DB_POOL_MAX=10',
      'DB_STATEMENT_TIMEOUT_MS=30000',
      'WORKER_CONCURRENCY=5',
      'SHUTDOWN_TIMEOUT_MS=25000',
    ]) {
      expect(output).toContain(`\n${line}\n`)
    }
  })
})
