import { describe, expect, it } from 'vitest'
import { EnvSchemaShape } from '@/configs/env.config'
import { render } from '@/scripts/generate-env-example'

describe('render', () => {
  const output = render(EnvSchemaShape)

  it('includes the generated-file header', () => {
    expect(output).toContain('# Generated by `pnpm env:example`. Do not edit by hand.')
  })

  it('includes every key from the schema shape', () => {
    for (const key of Object.keys(EnvSchemaShape)) {
      expect(output).toContain(`${key}=`)
    }
  })

  it('renders the description for a documented field as a comment', () => {
    expect(output).toContain('# Public origin of this API. PLACEHOLDER')
  })

  it('carries the placeholder note into every required-but-unused secret', () => {
    // JWT_ACCESS_SECRET is deliberately excluded here: token.utilities.ts
    // reads it to sign/verify access tokens, so its .describe() states what
    // it does instead of carrying this placeholder note — see
    // env.config.ts's own comment on that field.
    //
    // The remaining two are required by the schema and read by nothing in
    // src/. The .describe() text is the only thing that tells a cloner they
    // can put any 32-character string there for now, and .env.example is
    // where they will read it — so assert it actually reaches the file
    // rather than trusting that the generator picks descriptions up.
    for (const key of ['JWT_REFRESH_SECRET', 'SESSION_SECRET']) {
      const index = output.indexOf(`${key}=`)
      expect(output.slice(Math.max(0, index - 200), index)).toContain('PLACEHOLDER')
    }
  })

  it('describes what JWT_ACCESS_SECRET actually does, not a stale placeholder note', () => {
    const index = output.indexOf('JWT_ACCESS_SECRET=')
    const preceding = output.slice(Math.max(0, index - 200), index)
    expect(preceding).toContain('Signs and verifies access tokens')
    expect(preceding).not.toContain('PLACEHOLDER')
  })

  it('renders a schema default value', () => {
    expect(output).toContain('APP_PORT=4040')
  })

  it('comments out a genuinely optional field with no default', () => {
    expect(output).toContain('# OTEL_EXPORTER_OTLP_ENDPOINT=')
  })

  it('does not comment out a required field', () => {
    expect(output).toContain('\nDATABASE_URL=\n')
    expect(output).not.toContain('# DATABASE_URL=')
  })

  it('does not comment out a field with a default', () => {
    expect(output).toContain('\nAPP_PORT=4040\n')
  })
})
