// src/server.ts — owns the socket and the shutdown sequence.
import { type Server } from 'node:http'
import type { Worker } from 'bullmq'
import { createApp } from '@/app'
import { getEnv } from '@/configs/env.config'
import { shutdownOtel } from '@/observability/tracing'
import { closeDatabase } from '@/services/database.service'
import { logger } from '@/services/logger.service'
import { closeQueue } from '@/services/queue.service'
import { closeRedis } from '@/services/redis.service'

/**
 * Start listening.
 *
 * The port is a parameter, not read straight from the environment, because
 * `getEnv()` memoises: `database.service.ts` calls it at module scope, so
 * importing this module has already frozen the parsed environment before any
 * test body runs. A test that sets `process.env.APP_PORT` and then calls
 * `startServer()` would silently bind the configured port instead of an
 * ephemeral one, and would pass while testing the wrong thing.
 * @param port - Port to bind. Defaults to the configured one. Pass 0 to let the
 *   OS pick a free port, which is what makes the lifecycle test safe in parallel.
 * @returns The listening server.
 */
export function startServer(port: number = getEnv().APP_PORT): Server {
  return createApp().listen(port, () => {
    logger.info(`Listening on :${port}`)
  })
}

/**
 * Stop accepting connections, drain, then close dependencies.
 *
 * Order matters: the socket closes first so no new request can arrive and
 * find a closed pool. `server.close()`'s callback does not fire until every
 * in-flight connection has ended (on Node's HTTP server, closing also stops
 * accepting new connections on idle keep-alive sockets), so by the time
 * `closeDatabase()`/`closeRedis()` run here, no handler is still mid-request.
 *
 * The forced-exit backstop for a connection that never drains is NOT here —
 * `unicorn/no-process-exit` only allows `process.exit()` inside a
 * `process.on`/`process.once` callback, and this function is called directly,
 * not from one. The backstop timer lives in index.ts's signal handler
 * instead, which both satisfies the lint rule and keeps this function fully
 * testable (it can safely resolve without ever touching `process.exit`).
 *
 * Both workers close AFTER the socket and BEFORE the shared dependencies:
 * `Worker#close()` drains whatever job is currently being processed rather
 * than killing it mid-flight, and an in-flight job on either queue —
 * `processEmailJob` (email.worker.ts) calling `sendMail`, or
 * `processNotificationJob` (notification.worker.ts) inserting a row and
 * itself calling `addEmailJob` — needs the database and Redis still up.
 * Closing `closeQueue()` first would pull the connection both workers are
 * still using; closing it after is what lets the drain actually finish
 * cleanly. Both are optional so this still works for a `WORKER_ENABLED=false`
 * pod, which never started either.
 * `shutdownOtel()` runs last, after every other dependency has closed: it
 * flushes any spans still buffered for export, and closing it earlier would
 * risk dropping a span generated by the database/Redis/queue calls this
 * function's own earlier steps make.
 * @param server - The server returned by `startServer`.
 * @param emailWorker - The email worker, if this process started one (`WORKER_ENABLED`).
 * @param notificationWorker - The notification worker, if this process started one (`WORKER_ENABLED`).
 * @returns Resolves once everything is closed.
 */
export async function gracefulShutdown(
  server: Server,
  emailWorker?: Worker,
  notificationWorker?: Worker
): Promise<void> {
  await new Promise<void>((resolve) => server.close(() => resolve()))
  // `.filter(Boolean)` alone leaves this typed as `(Promise<void> |
  // undefined)[]` — `Boolean` is not a type predicate, so TypeScript never
  // narrows `undefined` back out, which trips
  // `@typescript-eslint/await-thenable` on an iterable that may still
  // contain a non-promise value. An explicit type-guard predicate removes
  // `undefined` at the type level too, not just at runtime.
  const workerCloses = [emailWorker?.close(), notificationWorker?.close()].filter(
    (close): close is Promise<void> => close !== undefined
  )
  await Promise.allSettled(workerCloses)
  await Promise.allSettled([closeDatabase(), closeRedis(), closeQueue()])
  await shutdownOtel()
}
