// src/server.ts — owns the socket and the shutdown sequence.
import { type Server } from 'node:http'
import { createApp } from '@/app'
import { getEnv } from '@/configs/env.config'
import { SERVER_DRAIN_TIMEOUT_MS } from '@/constants/global.constants'
import { shutdownOtel } from '@/observability/tracing'
import { closeDatabase } from '@/services/database.service'
import { closeAllStreams, markShuttingDown } from '@/services/lifecycle.service'
import { logger } from '@/services/logger.service'
import { closeNotificationSubscriber } from '@/services/notification-emitter.service'
import { closeQueue } from '@/services/queue.service'
import { closeRedis } from '@/services/redis.service'
import type { SupervisedWorkers } from '@/services/worker-supervisor.service'

/**
 * Start listening.
 *
 * The port is a parameter, not read straight from the environment, because
 * `getEnv()` memoises: `database.service.ts` calls it at module scope, so
 * importing this module has already frozen the parsed environment before any
 * test body runs. A test that sets `process.env.APP_PORT` and then calls
 * `startServer()` would silently bind the configured port instead of an
 * ephemeral one, and would pass while testing the wrong thing.
 * @param port - Port to bind. Defaults to the configured one. Pass 0 to let the
 *   OS pick a free port, which is what makes the lifecycle test safe in parallel.
 * A bind failure (EADDRINUSE, EACCES) logs one line and sets exit code 1.
 * `process.exit` is not allowed outside a `process.on` callback
 * (`unicorn/no-process-exit`), so index.ts owns the actual exit.
 * @returns The server, listening once its 'listening' event fires.
 */
export function startServer(port: number = getEnv().APP_PORT): Server {
  // Express 5 calls this on a bind failure too, with the error; the 'error' listener below logs that.
  const server = createApp().listen(port, (error) => {
    if (error === undefined) logger.info(`Listening on :${port}`)
  })
  server.once('error', (error) => {
    if (server.listening) {
      logger.error('Server error', { error })
      return
    }
    logger.error('Server failed to start', { error })
    process.exitCode = 1
  })
  return server
}

/**
 * Stop accepting connections, drain, then close dependencies.
 *
 * Order matters. Readiness flips to 503 first, then open SSE streams are
 * ended, since they would otherwise hold `server.close()` open forever. Then
 * the socket closes, so no new request finds a closed pool. Connections still
 * open after `SERVER_DRAIN_TIMEOUT_MS` are force-closed.
 *
 * The forced-exit backstop is not here: it lives in `createShutdownHandler`
 * (lifecycle.service.ts), called from index.ts's signal handler, so this
 * function never touches `process.exit` and stays testable.
 *
 * Both workers close AFTER the socket and BEFORE the shared dependencies:
 * `Worker#close()` drains whatever job is currently being processed rather
 * than killing it mid-flight, and an in-flight job on either queue —
 * `processEmailJob` (email.worker.ts) calling `sendMail`, or
 * `processNotificationJob` (notification.worker.ts) inserting a row and
 * itself calling `addEmailJob` — needs the database and Redis still up.
 * Closing `closeQueue()` first would pull the connection both workers are
 * still using; closing it after is what lets the drain actually finish
 * cleanly. `workers` is optional so this still works for a
 * `WORKER_ENABLED=false` pod, which never started any. It is read here, at
 * shutdown time, so Workers replaced after a Redis outage are the ones closed.
 * `shutdownOtel()` runs last, after every other dependency has closed: it
 * flushes any spans still buffered for export, and closing it earlier would
 * risk dropping a span generated by the database/Redis/queue calls this
 * function's own earlier steps make.
 * @param server - The server returned by `startServer`.
 * @param workers - The supervised Workers, if this process started them (`WORKER_ENABLED`).
 * @returns Resolves once everything is closed.
 */
export async function gracefulShutdown(server: Server, workers?: SupervisedWorkers): Promise<void> {
  markShuttingDown()
  closeAllStreams()
  await closeServer(server)
  await Promise.allSettled(workers ? [workers.close()] : [])
  await Promise.allSettled([
    closeDatabase(),
    closeRedis(),
    closeQueue(),
    closeNotificationSubscriber(),
  ])
  await shutdownOtel()
}

/**
 * Stop accepting connections and wait for open ones, force-closing any left after SERVER_DRAIN_TIMEOUT_MS.
 * @param server - The server to close.
 * @returns Resolves once the server has closed, or immediately if it was not listening.
 */
async function closeServer(server: Server): Promise<void> {
  // Resolves on ERR_SERVER_NOT_RUNNING too, so a second shutdown still completes.
  const closed = new Promise<void>((resolve) => server.close(() => resolve()))
  server.closeIdleConnections()
  // A keep-alive request still in flight here leaves an idle socket once it
  // ends; keep sweeping so the drain doesn't wait out keepAliveTimeout (5s).
  const sweep = setInterval(() => server.closeIdleConnections(), 250)
  const forceClose = setTimeout(() => server.closeAllConnections(), SERVER_DRAIN_TIMEOUT_MS)
  sweep.unref()
  forceClose.unref()
  await closed
  clearInterval(sweep)
  clearTimeout(forceClose)
}
