/**
 * @file ARCHITECTURE.md's environment table is generated by renderEnvTable()
 * from the schema's describe() text (`pnpm env:table`). The committed table must
 * match that output row for row, and no removed env name may appear in README.md or ARCHITECTURE.md.
 */
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { REMOVED_ENV_NAMES } from '@/configs/env-consistency.config'
import { EnvSchemaShape } from '@/configs/env.config'
import { renderEnvTable } from '@/scripts/generate-env-example'

const architecture = fs.readFileSync(path.resolve(process.cwd(), 'ARCHITECTURE.md'), 'utf8')
const rootDocuments = ['README.md', 'ARCHITECTURE.md']
  .map((name) => fs.readFileSync(path.resolve(process.cwd(), name), 'utf8'))
  .join('\n')
const HEADER = /^\| Variable +\| Required +\| Default +\| What it does +\|$/

/**
 * Split a Markdown table row into trimmed cells, so prettier's column
 * padding does not count as a difference. An escaped `\|` stays in its cell.
 * @param row - One table line.
 * @returns The row's cells.
 */
function cells(row: string): string[] {
  return row
    .trim()
    .replace(/^\|/, '')
    .replace(/\|$/, '')
    .split(/(?<!\\)\|/)
    .map((cell) => cell.trim())
}

/**
 * The environment table in ARCHITECTURE.md, from its header row to the first
 * line that is not a table row.
 * @returns Each row's cells, the separator row included.
 */
function tableRows(): string[][] {
  const lines = architecture.split('\n')
  const start = lines.findIndex((line) => HEADER.test(line))
  if (start === -1) throw new Error('ARCHITECTURE.md has no environment table header')
  const end = lines.findIndex((line, index) => index > start && !line.startsWith('|'))
  const table = end === -1 ? lines.slice(start) : lines.slice(start, end)
  return table.map((line) => cells(line))
}

// Prettier widens the separator's dashes to the column width.
const normalise = (row: string[]): string[] => row.map((cell) => (/^-+$/.test(cell) ? '---' : cell))

describe('ARCHITECTURE.md environment table', () => {
  it('matches renderEnvTable() row for row', () => {
    const expected = renderEnvTable(EnvSchemaShape)
      .split('\n')
      .map((line) => normalise(cells(line)))
    expect(tableRows().map((row) => normalise(row))).toEqual(expected)
  })

  it.each(Object.keys(REMOVED_ENV_NAMES))('never mentions the removed name %s', (name) => {
    expect(rootDocuments).not.toMatch(new RegExp(String.raw`\b${name}\b`))
  })
})
